inventory:  
  build: .
  command: npm start
  ports:
  - "8000:8000"
  links:
  - mongodb
  environment:
    - NODE_ENV=production
    - MONGODB_ADDRESS=mongodb
mongodb:  
  image: mongo
  volumes: 
    - '/data/db:/data/db'